### ISSUE TITLE
OpenAPI Generator Question

### ISSUE THREAD

**Issue by quentinlesceller** [dgarcia360/openapi-boilerplate#26]
Hi @dgarcia360 and thank you for the repo.

I have a question regarding the `openapi-generator`. When I run your project through it, it does not validate.

See:
```bash
~/openapi-boilerplate/src master
❯ openapi-generator validate -i openapi.yaml
Validating spec (openapi.yaml)
Errors:
	- attribute components.responses.$ref is not of type `object`
	- attribute components.schemas.$ref is not of type `object`
	- attribute components.schemas.Schema name $ref doesn't adhere to regular expression
	  ^[a-zA-Z0-9\.\-_]+$
	- attribute components.responses.Response key $ref doesn't adhere to regular expression
	  ^[a-zA-Z0-9\.\-_]+$
	- attribute components.parameters.Parameter name $ref doesn't adhere to regular expression
	  ^[a-zA-Z0-9\.\-_]+$

[error] Spec has 5 errors.
```

Thank you for your help.

**Comment by dgarcia360** [comment]
Hi @quentinlesceller, 

Could you please try the following?

1. Run the command ``npm run build`` first to bundle the spec in a single ``.yaml`` file.

> Some of the OpenAPI based tools support only a single file as an input. To continue using the spec with those tools, we’ll compile all the different files we’ve created with the command-line tool [swagger-cli](https://github.com/APIDevTools/swagger-cli).
> 
> Originally posted on https://davidgarcia.dev/posts/how-to-split-open-api-spec-into-multiple-files/

2. Run ``openapi-generator validate -i _build/openapi.yaml``.

**Comment by quentinlesceller** [comment]
Hi @dgarcia360,

Thank you for your answer. 
Indeed I believe the bundling should fix the error. It's too bad that openapi-generator kind of support multiples files but not completely though. i.e. https://github.com/coinbase/rosetta-specifications will be considered as valid by both impl. Anyway thank you for your answer :).
