### ISSUE TITLE
Unclear which license applies

### ISSUE THREAD

**Issue by yaSebastian** [dgarcia360/openapi-boilerplate#4]
There are 3 different license informations spread over the repository.

The package.json defines Apache 2.0 as the package license.
The LICENSE.md specifies MIT, as does the GitHub Repo, as does the header of the README.md
The bottom of the README.md includes a License chapter, that only lists a Copyright of the creator.

Could you please clarify and maybe homogenize the license of this repository/project?

**Comment by dgarcia360** [comment]
Thanks for the heads up! I've adapted the README, LICENSE, and package.json:

> Copyright (c) 2019-present David Garcia ([@dgarcia360](https://davidgarcia.dev)). Licensed under the [MIT License](LICENSE.md).
> 
> The Pet Store example used is derived from [OAI/OpenAPI-Specification](https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml), Copyright The Linux Foundation, Licensed under the [Apache License, Version 2.0](https://github.com/OAI/OpenAPI-Specification/blob/master/LICENSE).
